### ISSUE TITLE
0.18.x - ARM Builds Broken

### ISSUE THREAD

**Issue by ubergeek77** [ubergeek77/Lemmy-Easy-Deploy#12]
Good news for ARM users:

[Update plans for 0.18.x](https://github.com/ubergeek77/Lemmy-Easy-Deploy/issues/17)

---
~~The Lemmy team has removed the ARM-compatible Dockerfile in 0.18.0, and the existing Dockerfile ***is not compatible with ARM based systems***.~~

~~Unfortunately, this means Lemmy Easy Deploy ***cannot deploy 0.18.0 on ARM for the time being.***~~

~~This is an issue in Lemmy, not in Lemmy Easy Deploy. I will not be able to fix this until the Lemmy team fixes their ARM build issues (which have been a problem since 0.17.4).~~

~~Apologies everyone :(~~

**Comment by CrazyHenk44** [comment]
Great, thank you for saving me from a broken system.

**Comment by ubergeek77** [comment]
I am now building Lemmy Docker images for ARM, ARM64, and x86_64:

https://github.com/ubergeek77/lemmy-docker-multiarch

Lemmy Easy Deploy 1.2.0 will now use these images by default if possible, and fall back to the official images (x64 only) if my builds aren't available yet.

I've set up a bot to automatically build new Lemmy images as they are tagged. When Lemmy released 0.18.1, images on my repository should be available within 1-2 hours.
