### ISSUE TITLE
Please add email configuration to config.env

### ISSUE THREAD

**Issue by oz42** [ubergeek77/Lemmy-Easy-Deploy#15]
My instance cannot send any email ("this instance is not configured for email")

Proposal: these new entries and default values:
MAIL_HOST="localhost"
MAIL_PORT="25"
MAIL_USE_TLS="false"

**Comment by angryce** [comment]
# If true/1, also deploy the postfix server and configure Lemmy to send emails
# NOTE: Port 25 is USUALLY disabled on most server providers. For this reason, the email service is not well tested
# Feedback on the email service is appreciated!
USE_EMAIL="false"

Need to change that one to true in config.env, I also added dkim though so I get through the google block.

**Comment by oz42** [comment]
I would like to see an option to use my existing postfix localhost instance because that is the one that sends email through my "home base" main mailserver (smarthost) that is able to send emails anywhere. Otherwise the docker postfix needs a MAIL_SMARTHOST option in the env file so that it knows how to send.

**Comment by ubergeek77** [comment]
Sorry to disappoint, but pointing LED to your own postfix server is an advanced use case, and I don't have any servers that allow port 25 to be able to test something like this. In general, I leave advanced use cases up to the end user to modify this deployment script to suit their own needs.

As someone else mentioned, I do have an option in LED to spin up a postfix server for you, but that's only really provided "as-is" to mirror the official Lemmy deployment files. My providers block port 25, and I do not use email enough on my servers to request an exemption.

If you like, you're free to modify my script for your own use. If you're already running your own postfix server, there is a good chance you are technical enough to understand what you need to change. But for this project, this is too large of a change. Lots of changes would be needed to the docker-compose template to support talking to local machine services.

If someone wants to submit a PR adding more robust email support, and is willing to commit to assisting users with email-related issues, I'd be interested in merging it, but sadly this is not something I can do myself at the moment.

**Comment by ubergeek77** [comment]
By the way, I did end up adding more config options you may be interested in. I don't manage the networks to allow for the container to connect to `localhost`, so you may need to get creative and use a static Docker IP, but regardless more options are available now!
