### ISSUE TITLE
Lemmy container cannot reach database

### ISSUE THREAD

**Issue by aranym1** [ubergeek77/Lemmy-Easy-Deploy#3]
I've been troubleshooting this since last night with some other people:
https://lemmy.world/post/248800

This occurs whether or not I use the ansible install method or this.
The first two times I used ansible (wiping the OS each time), then wiped a third time and tried this.

The machine is just a regular x86 Ubuntu server 22.04 VPS - completely fresh install.
Now, onto the actual issue:

The lemmy container cannot reach the postgres database and continually restarts.
`sudo docker logs <id>` on the lemmy container returns (repeated many times over):

```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Error connecting to postgres://lemmy:PasswordRedacted@postgres:5432/lemmy', crates/db_schema/src/utils.rs:161:56
```

The postgres container appears to be functioning properly, here are its logs:

```
PostgreSQL init process complete; ready for start up.
2023-06-18 22:19:30.819 UTC [1] LOG:  starting PostgreSQL 15.3 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
2023-06-18 22:19:30.819 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2023-06-18 22:19:30.819 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2023-06-18 22:19:30.821 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2023-06-18 22:19:30.824 UTC [52] LOG:  database system was shut down at 2023-06-18 22:19:30 UTC
2023-06-18 22:19:30.833 UTC [1] LOG:  database system is ready to accept connections
2023-06-18 22:24:30.919 UTC [50] LOG:  checkpoint starting: time
2023-06-18 22:24:35.033 UTC [50] LOG:  checkpoint complete: wrote 44 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=4.110 s, sync=0.002 s, total=4.114 s; sync files=12, longest=0.001 s, average=0.001 s; distance=252 kB, estimate=252 kB
```

`sudo docker ps` output:

```
CONTAINER ID   IMAGE                        COMMAND                  CREATED          STATUS
PORTS                                                                                         NAMES
9eaa62ea6f99   caddy:latest                 "caddy run --config …"   23 minutes ago   Up 23 minutes
0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 443/udp, 2019/tcp   lemmy-easy-deploy-proxy-1
a10009ed128d   dessalines/lemmy-ui:0.17.4   "docker-entrypoint.s…"   23 minutes ago   Up 23 minutes
                                                                                              lemmy-easy-deploy-lemmy-ui-1
a166b1486d51   dessalines/lemmy:0.17.4      "/app/lemmy"             23 minutes ago   Restarting (101) 9 seconds ago                                                                                                 lemmy-easy-deploy-lemmy-1
08329653260b   asonix/pictrs:0.3.1          "/sbin/tini -- /usr/…"   23 minutes ago   Up 23 minutes
6669/tcp, 8080/tcp                                                                            lemmy-easy-deploy-pictrs-1
51af8f312511   postgres:15-alpine           "docker-entrypoint.s…"   23 minutes ago   Up 23 minutes
                                                                                              lemmy-easy-deploy-postgres-1
```

Modified portion of the config:

```
# The hostname for your instance
# Do NOT put http:// or https://
# ONLY put your domain here. Subdomains are ok.
LEMMY_HOSTNAME="lemmy.name"

# If you use Cloudflare, your Cloudflare API token. Otherwise leave blank.
# If present, the DNS-01 challenge will be used to obtain valid HTTPS certificates
# This is useful if you use the Cloudflare proxy. Do not forget to choose the Full (Strict) SSL mode!
# **This token must have access to edit the Zone where $LEMMY_HOSTNAME is**
CF_API_TOKEN=""

# Whether or not to build Lemmy from source rather than use the Docker Hub images
# This will significantly increase deploy time!
BUILD_FROM_SOURCE="false"

# The name of your Lemmy instance, will be displayed on the site header (only used during first-time setup)
# If you use special characters, please backslash-escape them.
SETUP_SITE_NAME="LemmyName"
```

**Comment by ubergeek77** [comment]
> This occurs whether or not I use the ansible install method or this.

This leads me to believe it is an internal Docker routing issue, and unfortunately I have limited ability to help with that. How did you install Docker? Did you use the default `apt` package available for Ubuntu? If so, visit the link in my Readme and try installing the "recommended" version of Docker. The Ubuntu-provided one is usually older and typically has many weird issues.

Note that it will show the same error if the password is simply just incorrect, so make sure that the password in the .env file and the lemmy.hjson file are correct. Also note, on the postgres side, that is an *initialization* password, so if it was somehow set to a different value the first time the postgres volume initiated, then changed later, it will cause this mismatch.

So:

- Try (re)installing Docker *using Docker's recommended instructions, NOT from Ubuntu's repository*
- Ensure an existing volume for postgres didn't already exist, and clear it + completely wipe the ./live directory and start over

If those do not resolve your internal network issue, unfortunately there is not much I can do.

**Comment by aranym1** [comment]
I used the recommended instructions (adding the docker repository and all) from here: https://docs.docker.com/engine/install/#server

There was no existing volume. This is on a new OS install.

I suspected there wouldn't be much you'd be able to do at this point, but thanks for the suggestions anyways.

**Comment by ubergeek77** [comment]
In the interest of troubleshooting, I can tell you that my deployment is running fine on Arch Linux. Maybe there is some strange Ubuntu iptables shenanigans going on?

**Comment by aranym1** [comment]
Clearing all iptables rules didn't change anything. I'll try a different OS and report back

**Comment by aranym1** [comment]
Using Debian worked! Out of curiosity, how do you add a new user as an instance admin?

**Comment by ubergeek77** [comment]
Users have to sign up for themselves, but the default mode is "approve," so new users (including yourself) should be able to use the sign up link and make an account.

If the Lemmy registration mode is set to "approve registrations," you as the admin will have to click on the notification bell and approve the account. Alternatively, you can click the settings cog to manage your instance settings, and allow open sign ups.

**Comment by aranym1** [comment]
I already set it to open registration, my question is regarding how to give a new account instance-wide admin powers (like the default lemmy admin account)

**Comment by ubergeek77** [comment]
[I actually had to look this up, I had no idea how](https://github.com/LemmyNet/lemmy-docs/commit/a9f65b10af3a6b676cf31ba3638f58b60ebe18fe)

So have the yet-to-be-admin user post a comment or post, then press the 3 dots on them and select "appoint as admin"

**Comment by aranym1** [comment]
Thanks! My instance is at https://lemmy.name - still working on the sidebar and things
