### ISSUE TITLE
Error when logging in the first time...

### ISSUE THREAD

**Issue by akzmonster** [ubergeek77/Lemmy-Easy-Deploy#31]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes/No

**Describe the issue**
> I use the provided password and username for admin and get this error every time: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

**Diagnostic Information**
> Run `./deploy.sh -d` and paste the output below:
```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.2, build cb74dfc)
Detected compose: docker compose (Docker Compose version v2.18.1)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 5.19.0-23-generic (x86_64)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:           465Mi       305Mi        13Mi        24Mi       146Mi       114Mi
Swap:             0B          0B          0B

DISTRO:
----------------------------
PRETTY_NAME="Ubuntu 22.10"
NAME="Ubuntu"
VERSION_CODENAME=kinetic
UBUNTU_CODENAME=kinetic
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.2.6

IMAGE                                CREATED         STATUS
caddy:latest                         4 minutes ago   Up 4 minutes
ghcr.io/ubergeek77/lemmy-ui:0.18.0   4 minutes ago   Up 4 minutes
ghcr.io/ubergeek77/lemmy:0.18.0      4 minutes ago   Up 4 minutes
asonix/pictrs:0.4.0-beta.19          4 minutes ago   Up 4 minutes
postgres:15-alpine                   4 minutes ago   Up 4 minutes

Integrity:
    789dff42875ab8c43692ddeef7600ef3b3c0a5abf24d84efe6cdae49a46e7ce7  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    d9928baea61975bd432e1a4a7439c04468547c9b42e2bb483c6f18d9438665eb  ./templates/docker-compose.yml.template
    a74770730fd0e809d44e5247e1300be04c2b664be13d06bfec00296e3e63861b  ./templates/lemmy-email.snip
    c834cdce9eaf77f38155b404724fdfe66845575386ee516987452aa715642a6f  ./templates/lemmy.hjson.template

Custom Files:
*** No custom files ***

==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: false
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: false
         SMTP_PORT: 25
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.0;0.18.0

total 36K
drwxr-xr-x 2 0 0 4.0K Jul  6 07:47 caddy
-rw-r--r-- 1 0 0   32 Jul  6 07:47 caddy.env
-rw-r--r-- 1 0 0 1.7K Jul  6 07:47 docker-compose.yml
-rw-r--r-- 1 0 0   50 Jul  6 07:47 lemmy.env
-rw-r--r-- 1 0 0  475 Jul  6 07:47 lemmy.hjson
-rw-r--r-- 1 0 0   49 Jul  6 07:47 pictrs.env
-rw-r--r-- 1 0 0   36 Jul  6 07:47 postfix.env
-rw-r--r-- 1 0 0   51 Jul  6 07:47 postgres.env
-rw-r--r-- 1 0 0   14 Jul  6 07:48 version

```

**Comment by akzmonster** [comment]
> When you access Lemmy from your browser, do you use the exact domain you have set in LEMMY_HOSTNAME exactly

Yes, and when I enter the domain the page loads perfectly,

> with no ports set?

I don't know how to do that so, no?

I'll have to try the commands later today and I'll get back then.

It's a digital ocean droplet with (what is supposed to be) 2GB of ram. Not sure why it shows less. I rebuilt the droplet dozens of times because this process is such a mess. I wouldn't imagine that would do anything to the VM allocation but maybe it's shared?

**Comment by akzmonster** [comment]
I tried to run the curl resolve HTTPS and it does nothing at all. It's frozen. I had to restart the SSH after a few minutes. And the only error is:

> lemmy-easy-deploy-lemmy-1  | 2023-07-06T19:03:33.039550Z  WARN Error encountered while processing the incoming HTTP request: lemmy_server::root_span_builder: Origin is not allowed to make this request

**Comment by ubergeek77** [comment]
Ok, that's what I thought. You are encountering a known Lemmy issue that will be fixed in 0.18.1:

https://www.github.com/LemmyNet/lemmy/pull/3421

As for HTTPS not working, is it possible you do not have HTTPS certificates? This situation seems a bit strange to me.

When you go to the browser, do you access Lemmy like this:

```
https://LEMMY_HOSTNAME
```

or like this?

```
https://LEMMY_HOSTNAME:443
```

If your instance is not available to the public at exactly ports 80 and 443, not only will you see the error you are having, but Caddy will also be unable to request HTTPS certificates.

I am not familiar with firewall rules on DigitalOcean, but is it possible you are forwarding some non-80/non-443 port to your instance, and accessing it directly like in my second example above?

**Comment by akzmonster** [comment]
I just type in the domain, and the browser adds the https to the front of it. I definitely did not implement my own port forwarding of any kind. I have tried using all 3 of Lemmy's guides and none of them addressed port forwarding. I've watched several tutorials (that are now deprecated) that use digital ocean and the ONLY thing they modified in the droplet was the DNS A record. And I start with a completely fresh Ubuntu 22.10 build then apt-get updates/upgrades. 

I would like to add that your method has gotten me farther than anyone else! And your steps were so easy to follow and did everything you said I should expect. I wish Lemmy made theirs like yours. And I envy your expertise with GNU!

**Comment by ubergeek77** [comment]
I'm glad this project got you the furthest!

As a last resort, you can try the latest RC that has the CORS error fix:

```
./deploy.sh -l 0.18.1-rc.10 -w 0.18.1-rc.11 -f
```

There is still the question of why this is happening in the first place, since I still have no idea why this is happening, but this could solve it for you!

**Comment by akzmonster** [comment]
Well, the only thing that happens outside of your guide is when I do apt-get upgrade, it asks if I want to keep the original ssh settings. Otherwise, I wait for that to finish then go straight into your guide. Were there any other dependencies that a practiced linuxer would know to do first?

This is the process that I use to install docker: https://docs.docker.com/engine/install/ubuntu/

I start with running the removal line and then into the 3 main install blocks and then docker ce. I finish with the hello world test and it works every time. Then it's right back to your guide. I'll verify later today that my ram is 2GB. And I'll try the latest RC. I am getting so excited. I've never done anything like this before.

**Comment by ubergeek77** [comment]
> Well, the only thing that happens outside of your guide is when I do apt-get upgrade, it asks if I want to keep the original ssh settings. Otherwise, I wait for that to finish then go straight into your guide. Were there any other dependencies that a practiced linuxer would know to do first?

Nope, you can just accept the default there, that wouldn't impact everything. And my script will warn you if any commmands it needs are missing. It's pretty lightweight, it only needs Docker.

I'm glad you're using the official version of Docker! The Ubuntu version causes quite a few headaches 😅 

Sounds like you did everything right to me, at least as far as this script is concerned. I don't have a DigitalOcean account, but maybe they route things weirdly and don't pass a header or something. Who knows.

But based on what you have told me, I am 99% sure if you install the latest RC like I posted above, this should fix everything for you. And if it doesn't, I might be able to help more, but at that point it's probably just a bug in Lemmy itself.

Fingers crossed that works for you!

**Comment by akzmonster** [comment]
Same issue even after latest RC. The only difference is when I click "login" after entering the correct admin credentials, the login turns into a spinning arrow and then does nothing else, just spins. If I click it again, I get the error message.

**Comment by ubergeek77** [comment]
Unfortunately, I do not know what else to suggest, I am very sorry :(

You could take a look at the `proxy` (Caddy) logs to see what information that provides. If you are truly using `rc.10`, which had the CORS fix, then it means the Lemmy backend isn't being sent the right header from the UI for some reason.

I am by no means a perfect developer, but there is very little in my script here that could cause something like that. All this does is make a copy of the official Lemmy docker-compose.yml with autogenerated files that make the configuration go smoothly. I have tested on many different environments across different server hosts and architectures, with many users reporting success, but nothing like this has ever happened. Sadly, you may need to file an official Lemmy bug about this.

As a longshot, is your hostname (`cat /etc/hostname`) anything that would conflict with Lemmy? Such as being named `lemmy` (lowercase), `lemmy-ui`, or your Lemmy domain name. If so, I would recommend changing it first and then redeploying.

Finally, have you tried on other hosting providers besides DigitalOcean? I can tell you that this script has several reports of success on Linode and AWS, and personally I test on Vultr which works well. Perhaps there is something odd about DigitalOcean's routing.

**Comment by akzmonster** [comment]
HEY!!!

I rebuilt the image, did everything again, then ran the RC update and it worked!!! I'm logged in!!! Check it out: Alaska.Community

Thank you so much!

**Comment by ubergeek77** [comment]
That's great news! It really was that CORS stuff after all! I'm glad to hear you got running!

Once `0.18.1` is released officially, don't forget to run `./deploy.sh -f` to install it. You will need the `-f` since you installed `rc` versions manually (but if you forget, it's ok, the script tells you what to do if you run it without it).

Enjoy Lemmy and welcome to the Fediverse!
