### ISSUE TITLE
Port number Confusion

### ISSUE THREAD

**Issue by izz-j** [ubergeek77/Lemmy-Easy-Deploy#32]
First off thank you for making this as you have saved me a lot of headache with Lemmy's original documentation.
Sorry for the simple question. I have followed the documentation and I have deployed Lemmy-Easy-Deply on my raspberry pi with no errors. But I am confused about which port I should be typing in my address bar to actually access the site from my browser?

**Comment by ubergeek77** [comment]
If you haven't changed the port in config.env, then it will just be port 80/443. You should not have to specify a port, you simply go to your domain as specified in LEMMY_HOSTNAME

If you do not have a domain, it's more tricky. Of course, you won't be able to federate or reach your instance online without one. You can still use it locally without a domain, but you'll have to set CADDY_DISABLE_TLS to `true`, and change LEMMY_HOSTNAME to whatever host you want to use Lemmy on.

There are a few notes about CORS errors that I could ramble on about... or you can give me a few more details about your use case, and I can give you more specific help :)

**Comment by izz-j** [comment]
Thank you for the quick response. Yes I will give you more detail. I do not have a domain name yet. I have just been using my raspberry pi's public ip to ssh  from my computer to test the server out in my LAN. I set LEMMY_HOSTNAME to my pi's public ip. 

I will try what you suggested.

**Comment by ubergeek77** [comment]
Sounds good. Just a few warnings:

- Once you start using it, if you want to transition to a domain name later, you won't be able to, as your Lemmy instance's hostname/private keys will be calculated against that IP address.
- You may need to also set `LEMMY_TLS_ENABLED` to `false`
- There was a quirk of Lemmy that could cause JSON errors in the UI when it's being used like this. That was fixed already and will be available in 0.18.1, but you might encounter that issue the way you're trying to use it.
- Since federation requires HTTPS, and you can't use that without a domain, you will not be able to federate with other instances. This means you'll be limited to only posts made on your instance.

If you ever feel like you want to start over so you can set a hostname, you can delete your Docker volumes like this:

```
./deploy.sh --shutdown
docker volume rm lemmy-easy-deploy_caddy_config                                           docker volume rm lemmy-easy-deploy_caddy_data                                             docker volume rm lemmy-easy-deploy_pictrs_data                                            docker volume rm lemmy-easy-deploy_postgres_data
```

Just don't forget to change the settings in `config.env` back!

**Comment by izz-j** [comment]
Thank you for the warnings and being very informative.

I have made the changes in config.env. But when I try to connect to the server in my browser (firefox) I get:

`SSL_ERROR_INTERNAL_ERROR_ALERT`

I checked firewall, port 80 is open. So my port is fine. I have cleared my browser's cache. I am currently troubleshooting this issue. Do you know what it could be?

**Comment by ubergeek77** [comment]
Did you set `CADDY_DISABLE_TLS` to `true`? You'll have to do that as well.

**Comment by izz-j** [comment]
Yes I did.

**Comment by ubergeek77** [comment]
Hmmm... Caddy should only be trying to use SSL if you've set those options and regenerated the config with `./deploy.sh -f`. You can confirm this if you run `cat ./live/caddy/Caddyfile`. You should see `http://{$LEMMY_HOSTNAME}` in that last block.

If that doesn't work, unfortunately I do not have any advice to offer besides getting a domain name, as that is the primary use case for this. Apologies!

**Comment by izz-j** [comment]
Turns out last time I `./deploy.sh` I forgot `-f`. (Facepalm). I cleared my browser's cache and I was able to reach my server via browser. So far things are working fine. Thank you for your patience and all the tips you gave me!

**Comment by ubergeek77** [comment]
Perfect! Happy to have helped :)

**Comment by izz-j** [comment]
Sorry to reopen this again but I thought it appropriate since the issue is a continuation from your advice. So after testing from my LAN server with much joy and success,  I decided it was time to acquire a domain name. Cleaned my `live` directory, changed hostname to domain name and changed the settings back in `config.env`. Then I did `./deploy.sh -f`. Watched it deploy successfully. I cleared my browser's cache. Entered the new domain name in my browser. And Somehow I have got this error again:

 `SSL_ERROR_INTERNAL_ERROR_ALERT`

Maybe it is another silly mistake on my end haha. But I am trying to figure out why this is.

**Comment by ubergeek77** [comment]
Did you delete the original volumes as well? I assume yes, because I have a warning in the script if you have not.

You can post your diagnostic information (`./deploy.sh -d`) and I can take a look, but I can tell you that Firefox (although my preferred and favorite browser) is pretty unreliable with cache changes, especially with HTTPS. I usually have to do my testing in Chrome just because of this.

Can you try again in an incognito window in Chrome or Firefox?

If it's still happening, post your diagnostic info and we can go from there 👍

**Comment by izz-j** [comment]
Yes I deleted the original volumes. I also just tried incognito mode on firefox but that did not work.
Here are my settings and directory permissions from `./deploy.sh -d`. 
`
==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: false
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: false
         SMTP_PORT: 25
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.1;0.18.1

total 36K
drwxr-xr-x 2 1000 1000 4.0K Jul  7 15:16 caddy
-rw-r--r-- 1 1000 1000   27 Jul  7 15:52 caddy.env
-rw-r--r-- 1 1000 1000 1.7K Jul  7 15:52 docker-compose.yml
-rw-r--r-- 1 1000 1000   50 Jul  7 15:16 lemmy.env
-rw-r--r-- 1 1000 1000  467 Jul  7 15:52 lemmy.hjson
-rw-r--r-- 1 1000 1000   49 Jul  7 15:16 pictrs.env
-rw-r--r-- 1 1000 1000   31 Jul  7 15:52 postfix.env
-rw-r--r-- 1 1000 1000   51 Jul  7 15:16 postgres.env
-rw-r--r-- 1 1000 1000   14 Jul  7 15:53 version
`
I don't really see what could be wrong. Though I just acquired and setup the domain. But I don't think DNS propagation would effect SSL.

**Comment by ubergeek77** [comment]
- May I see the rest of the output? Those hashes under "Integrity" do not contain sensitive information, just the hashes for the files. They are safe to post.
- Are you behind any proxies, especially the Cloudflare proxy?
- This might be a Firefox-specific issue that involves a domain very quickly changing its HTTPS support status: https://support.mozilla.org/en-US/questions/1130471
   - For the time being, can you please try Chrome instead to rule this out?

**Comment by izz-j** [comment]
Ok thank you. I wasn't sure if the hashes contained sensitive information. Here is the entire output. I tried Safari and Microsoft Edge on other devices and I also got the same warning of the connection not being secure. I feel like this should rule the browser being a problem. But I could install chrome just for the heck of it. No I am not behind Cloudflare or any other proxy. 

```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.2, build cb74dfc)
Detected compose: docker compose (Docker Compose version v2.18.1)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 6.1.21-v7+ (armv7l)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:           921Mi       177Mi       183Mi        14Mi       561Mi       675Mi
Swap:           99Mi       1.0Mi        98Mi

DISTRO:
----------------------------
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_CODENAME=bullseye
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.2.7

IMAGE     CREATED   STATUS

Integrity:
    0dcb79d994394bd204f7034ce2bd58838d9d1187262463c95d3abb70a1d6d421  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    d9928baea61975bd432e1a4a7439c04468547c9b42e2bb483c6f18d9438665eb  ./templates/docker-compose.yml.template
    1c202b1b6e87c65b2fcda6035c9fe3f8631d76662907ffd38f24b14686e30647  ./templates/lemmy-email.snip
    c834cdce9eaf77f38155b404724fdfe66845575386ee516987452aa715642a6f  ./templates/lemmy.hjson.template

Custom Files: 
*** No custom files ***

==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: false
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: false
         SMTP_PORT: 25
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.1;0.18.1

total 36K
drwxr-xr-x 2 1000 1000 4.0K Jul  7 15:16 caddy
-rw-r--r-- 1 1000 1000   27 Jul  7 15:52 caddy.env
-rw-r--r-- 1 1000 1000 1.7K Jul  7 15:52 docker-compose.yml
-rw-r--r-- 1 1000 1000   50 Jul  7 15:16 lemmy.env
-rw-r--r-- 1 1000 1000  467 Jul  7 15:52 lemmy.hjson
-rw-r--r-- 1 1000 1000   49 Jul  7 15:16 pictrs.env
-rw-r--r-- 1 1000 1000   31 Jul  7 15:52 postfix.env
-rw-r--r-- 1 1000 1000   51 Jul  7 15:16 postgres.env
-rw-r--r-- 1 1000 1000   14 Jul  7 15:53 version
```

**Comment by izz-j** [comment]
Ok so the internal error was due to a router issue. Now everything is working fine and smoothly. Thank you again!
