### ISSUE TITLE
troubles putting Lemmy-Easy-Deploy behind a reverse proxy

### ISSUE THREAD

**Issue by OhaDerErste** [ubergeek77/Lemmy-Easy-Deploy#37]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes/No
Yes
**Describe the issue**
> What happened? Post any relevant log snippets.
Im trying to run Lemmy without ssl behind a Caddy Reverse proxy and Im getting a "The page isn’t redirecting properly" Error.
My Caddy config:
```
https://lemmy.ohaa.xyz:443 {
       reverse_proxy 10.0.0.140
}
``` 

**Diagnostic Information**
> Run `./deploy.sh -d` and paste the output below:
```

==== Docker Information ====
Detected runtime: docker (Docker version 24.0.4, build 3713ee1)
Detected compose: docker compose (Docker Compose version v2.19.1)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 6.2.16-3-pve (x86_64)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:           2.0Gi       283Mi       1.5Gi        16Mi       219Mi       1.7Gi
Swap:             0B          0B          0B

DISTRO:
----------------------------
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_CODENAME=bullseye
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.2.7

IMAGE                                CREATED         STATUS
caddy:latest                         5 minutes ago   Up 5 minutes
ghcr.io/ubergeek77/lemmy-ui:0.18.1   5 minutes ago   Up 5 minutes
ghcr.io/ubergeek77/lemmy:0.18.1      5 minutes ago   Up 5 minutes
asonix/pictrs:0.4.0-beta.19          5 minutes ago   Up 5 minutes
postgres:15-alpine                   5 minutes ago   Up 5 minutes

Integrity:
    0dcb79d994394bd204f7034ce2bd58838d9d1187262463c95d3abb70a1d6d421  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    d9928baea61975bd432e1a4a7439c04468547c9b42e2bb483c6f18d9438665eb  ./templates/docker-compose.yml.template
    1c202b1b6e87c65b2fcda6035c9fe3f8631d76662907ffd38f24b14686e30647  ./templates/lemmy-email.snip
    c834cdce9eaf77f38155b404724fdfe66845575386ee516987452aa715642a6f  ./templates/lemmy.hjson.template

Custom Files: 
*** No custom files ***

==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: true
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: false
         SMTP_PORT: 25
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.1;0.18.1

total 36K
drwxr-xr-x 2 0 0 4.0K Jul  7 21:27 caddy
-rw-r--r-- 1 0 0   30 Jul  7 21:27 caddy.env
-rw-r--r-- 1 0 0 1.7K Jul  7 21:27 docker-compose.yml
-rw-r--r-- 1 0 0   50 Jul  7 21:27 lemmy.env
-rw-r--r-- 1 0 0  464 Jul  7 21:27 lemmy.hjson
-rw-r--r-- 1 0 0   49 Jul  7 21:27 pictrs.env
-rw-r--r-- 1 0 0   34 Jul  7 21:27 postfix.env
-rw-r--r-- 1 0 0   51 Jul  7 21:27 postgres.env
-rw-r--r-- 1 0 0   14 Jul  7 21:29 version
```

**Comment by ubergeek77** [comment]
I am very sorry, but with such limited time to work on Lemmy-Easy-Deploy, issues related to using a reverse proxy are not something I can spend significant time supporting. From the [Troubleshooting page](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md):

> - I have some special use case involving a separate webserver and reverse proxies.
>	- Sorry, but as that kind of configuration can vary significantly, this is not a use case I can support. Lemmy-Easy-Deploy is intended for users new to hosting and do not have any webservers set up at all.
>	- However, I do provide you with plenty of options in `config.env` that may help you configure Lemmy-Easy-Deploy to work with this kind of setup. Hopefully those options will be of use to you!

However, I can give you some advice. The Caddy config in Lemmy-Easy-Deploy is expecting a Host header of whatever you set in LEMMY_HOSTNAME. In your external Caddy config, you don't seem to be setting that header. My version of Caddy has to "think" it is being accessed by hostname, not IP address. If you take a look at `./live/caddy/Caddyfile`, you will see a block that starts with `{$LEMMY_HOSTNAME}`. You must send a request to my Caddy deployment on that host.

I wish you the best of luck!
