### ISSUE TITLE
Get 404 error in Firefox console when trying to login as admin

### ISSUE THREAD

**Issue by sh4d0wph03n1x** [ubergeek77/Lemmy-Easy-Deploy#39]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
> Yes

**Describe the issue**
> What happened? Post any relevant log snippets.
Whenever I try to login on my instance (new install) it loads quickly, then does nothing. Upon opening the console in Firefox, it shows a 404 error and states that "https://my-lemmy-instance.com/api/v3/user/login" is not found. Made a test account just fine, cannot log into it due to needing to approve it with the admin account.

```
Some cookies are misusing the recommended “SameSite“ attribute 2
Source map error: Error: request failed with status 400
Resource URL: https://lemmy.lat/css/themes/darkly.css
Source Map URL: darkly.css.map
XHRPOST
https://lemmy.lat/api/v3/user/login
[HTTP/2 404 Not Found 84ms]
```

**Diagnostic Information**
> Run `./deploy.sh -d` and paste the output below:
```
==== Docker Information ====
Detected runtime: docker (Docker version 24.0.2, build cb74dfc)
Detected compose: docker compose (Docker Compose version v2.18.1)
   Runtime state: OK

==== System Information ====
      OS: Linux
  KERNEL: 5.15.0-76-generic (x86_64)
HOSTNAME: OK
   SHELL: bash
  MEMORY:
               total        used        free      shared  buff/cache   available
Mem:            23Gi       914Mi        15Gi        49Mi       7.2Gi        22Gi
Swap:           51Gi          0B        51Gi

DISTRO:
----------------------------
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
----------------------------

==== Lemmy-Easy-Deploy Information ====
Version: 1.2.7

IMAGE                                CREATED          STATUS
caddy:latest                         18 minutes ago   Up 18 minutes
ghcr.io/ubergeek77/lemmy-ui:0.18.1   18 minutes ago   Up 18 minutes
ghcr.io/ubergeek77/lemmy:0.18.1      18 minutes ago   Up 18 minutes
asonix/pictrs:0.4.0-beta.19          18 minutes ago   Up 18 minutes
postgres:15-alpine                   18 minutes ago   Up 18 minutes

Integrity:
    0dcb79d994394bd204f7034ce2bd58838d9d1187262463c95d3abb70a1d6d421  ./deploy.sh
    1e9b0c0988998dcc33cb0fbfdb0e1679229424e724f898b797380adc7d102446  ./templates/Caddy-Dockerfile.template
    c1202e70662dd2228da36a35a0f38ec8fc81bec8964d7315d02e8671a58dd7d7  ./templates/Caddyfile.template
    2537678c7971df36c1ed95f4228d3cfcb15bb4a28a60d939eaf8dd75b5d64a36  ./templates/cloudflare.snip
    c9cb4c5fee12930e17798a02ae1bd12e2dc69e149a394c24511bc9d4e6b776d4  ./templates/compose-email.snip
    c494a610bcb4cd1cfc0a4fe4fb0f6d437b2a84a0ad1625daee240e6dd6f1c910  ./templates/compose-email-volumes.snip
    d9928baea61975bd432e1a4a7439c04468547c9b42e2bb483c6f18d9438665eb  ./templates/docker-compose.yml.template
    1c202b1b6e87c65b2fcda6035c9fe3f8631d76662907ffd38f24b14686e30647  ./templates/lemmy-email.snip
    c834cdce9eaf77f38155b404724fdfe66845575386ee516987452aa715642a6f  ./templates/lemmy.hjson.template

Custom Files:
*** No custom files ***

==== Settings ====
        CLOUDFLARE: No
 CADDY_DISABLE_TLS: false
   CADDY_HTTP_PORT: 80
  CADDY_HTTPS_PORT: 443
 LEMMY_TLS_ENABLED: true
      ENABLE_EMAIL: false
         SMTP_PORT: 25
    ENABLE_POSTFIX: false
POSTGRES_POOL_SIZE: 5

==== Generated Files ====
Deploy Version: 0.18.1;0.18.1

total 36K
drwxrwxr-x 2 1001 1002 4.0K Jul  7 03:30 caddy
-rw-rw-r-- 1 1001 1002   25 Jul  8 00:39 caddy.env
-rw-rw-r-- 1 1001 1002 1.7K Jul  8 00:39 docker-compose.yml
-rw-rw-r-- 1 1001 1002   50 Jul  7 03:30 lemmy.env
-rw-rw-r-- 1 1001 1002  459 Jul  8 00:39 lemmy.hjson
-rw-rw-r-- 1 1001 1002   49 Jul  7 03:30 pictrs.env
-rw-rw-r-- 1 1001 1002   29 Jul  8 00:39 postfix.env
-rw-rw-r-- 1 1001 1002   51 Jul  7 03:30 postgres.env
-rw-rw-r-- 1 1001 1002   14 Jul  8 00:39 version

```

**Comment by ubergeek77** [comment]
What happens if you visit this URL:

```
https://your-instance.com/api/v3/site
```

- If it loads and you see a JSON response, then my routing is working properly, and I may not be able to help you.
- If it also shows 404, then I will need to look into why it broke, but I have no idea why it would break so suddenly.

**Comment by sh4d0wph03n1x** [comment]
Yep I got a JSON response. Where do I report my issue?

**Comment by ubergeek77** [comment]
Most likely the UI issue tracker:

https://github.com/LemmyNet/lemmy-ui/issues

However, note that `https://my-lemmy-instance.com/api/v3/user/login` is a POST-only endpoint. If you try running a GET request to it, it will respond 404.

Are you sure you can't log in using the generated admin password? Be sure to not copy the quotation marks, as they are not part of the password.

**Comment by sh4d0wph03n1x** [comment]
Yeah, the password is correct. 
![Screenshot 2023-07-07 at 9 13 49 PM](https://github.com/ubergeek77/Lemmy-Easy-Deploy/assets/26177794/58c8d981-ad0c-475c-8d78-1e9d208a2df4)
This is what shows, it is making a POST request I believe.

**Comment by sh4d0wph03n1x** [comment]
Wait hold on, when under the "Response" tab, it says "Cannot find username or email"

**Comment by ubergeek77** [comment]
I've just deployed a fresh 0.18.1 instance and sadly cannot reproduce this issue, I can log in as normal.

And yes, I just tried what you mention, if I give it an intentionally bad password, the `/login` endpoint also returns 404 just like this. So your password is simply incorrect.

Note that the default username is `lemmy`, not `admin`.

**Comment by sh4d0wph03n1x** [comment]
I need sleep oh my god. I am so sorry, I have been typing in `admin` rather than `lemmy`. My bad, sorry for the trouble.

**Comment by ubergeek77** [comment]
No problem!

One more quick note - if you wanted to start over and have your admin user be `admin`, you can absolutely do that, just set `SETUP_ADMIN_USER` to `admin` in `config.env`

Note this is only used for *setup*, so only as long as the `postgres` volume does not exist. If you wanted to clear out everything and change your user to `admin`, do the following (this will delete your instance and all generated secrets):

```
# Change SETUP_ADMIN_USER in config.env to whatever you like, such as admin
./deploy.sh --shutdown
docker volume rm lemmy-easy-deploy_postgres_data
rm -rf ./live
./deploy.sh
```

Have fun using Lemmy! And enjoy a good rest! 😅

**Comment by sh4d0wph03n1x** [comment]
Good to know, thanks. And thanks for the prompt replies, this is a great project and you're a great dev!
