### ISSUE TITLE
No federation?

### ISSUE THREAD

**Issue by allywilson** [ubergeek77/Lemmy-Easy-Deploy#46]
Hello,
        This may be the wrong place to ask for help, as I think the issue is most likely with Lemmy or AWS, but I thought I'd ask anyway.

I'm deploying your lemmy-easy-deploy in AWS (on AL2023, aarch64). It deploys successfully, however I cannot search for communities on other instances, no instances appear in federation.

I can install ping in the lemmy container and confirm name resolution and external connectivity, but I can't see an obvious error in any logs. 

I've (hopefully) sanitised the docker logs and attached them here. Wondering if you could point me in the right direction?

Thanks in advance.
[docker_logs.tar.gz](https://github.com/ubergeek77/Lemmy-Easy-Deploy/files/12061795/docker_logs.tar.gz)

**Comment by ubergeek77** [comment]
Please do not skip the issue template, it is there for a reason :)
