### ISSUE TITLE
How do I set it up to use a mounted data disk in my azure ubuntu vm?

### ISSUE THREAD

**Issue by SecondPartySoftware** [ubergeek77/Lemmy-Easy-Deploy#47]
**Did you check the [FAQ & Troubleshooting section](https://github.com/ubergeek77/Lemmy-Easy-Deploy/blob/main/TROUBLESHOOTING.md) for answers to common questions and issues?**
Yes

**Describe the issue**
I'm not very proficient with setting up services like this.
I have a 1tb data drive mounted to /data but I don't know how to get the deployment to use it...

azureuser@lemmy:/mnt$ lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
sda     0:0:0:0      30G
├─sda1             29.9G /
├─sda14               4M
└─sda15             106M /boot/efi
sdb     0:0:0:1       4G
└─sdb1                4G /mnt
sdc     1:0:0:0       1T
└─sdc1             1024G /data

I made a previous deployment and I'm pretty sure it just used the os disk under / which only has 30gb.

Any help would be appreciated!

**Diagnostic Information**

**Comment by ubergeek77** [comment]
Unfortunately, as this script relies on Docker, I have no ability to automatically change the directory your data is mounted on. You will have to do some tinkering to change the Docker root directory. I can point you in the right direction, but that is as much as I can do sadly.

This should be what you need, though!

https://stackoverflow.com/questions/69749285/docker-named-volume-on-another-partition-on-another-hard-drive

**Comment by SecondPartySoftware** [comment]
Thank you for the prompt response! Your work has been very helpful :)

**Comment by SecondPartySoftware** [comment]
Cool, I think it is all working after changing the default docker volume directoy!

azureuser@lemmy:~/Lemmy-Easy-Deploy$ docker volume inspect lemmy-easy-deploy_pictrs_data
[
    {
        "CreatedAt": "2023-07-15T19:26:38Z",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "lemmy-easy-deploy",
            "com.docker.compose.version": "2.19.1",
            "com.docker.compose.volume": "pictrs_data"
        },
        "Mountpoint": "/data/docker/volumes/lemmy-easy-deploy_pictrs_data/_data",
        "Name": "lemmy-easy-deploy_pictrs_data",
        "Options": null,
        "Scope": "local"
    }
]
