### ISSUE TITLE
Support custom environment variables

### ISSUE THREAD

**Issue by LRMAN0989** [ubergeek77/Lemmy-Easy-Deploy#9]
I set up my instance and couldn't figure out why it wasn't federating; eventually realized the docker-compose.yml.template had the wrong environment variable. After changing it, my instance now federates

I would make a pull request but I know nothing about git

**Comment by ubergeek77** [comment]
I don't think that's related to your federation issues. That environment variable was pulled directly from Lemmy's example deployment:

https://github.com/LemmyNet/lemmy/blob/1386039eceb5f49bcb3e060462f923c0d56b8721/docker/prod/docker-compose.yml#L54

Can you tell me where you saw `LEMMY_UI_HTTPS` used?

**Comment by LRMAN0989** [comment]
I found it on the Lemmy-UI readme
https://github.com/LemmyNet/lemmy-ui/blob/main/README.md

I changed the setting and instantly started federation, so not sure what else I could have done that

**Comment by LRMAN0989** [comment]
Fair enough! I think it must default to false though, the only reason I went looking for it is because I saw in the logs a line saying "ishttps: false" or something like that, and after changing the variable it shows true now

The instance was working fine besides federation so not sure what the setting does break if set wrong then

**Comment by ubergeek77** [comment]
Haven't really gotten to this yet, sorry, I was working on a ton of other things.

This is a feature I want to add, so I'm hijacking this issue to track it. In the future I'll allow the user to add custom environment variables.

The one you were trying to use is *technically* only present for debugging purposes by the official Lemmy team, so I no longer explicitly set it, but you can still edit your `docker-compose.yml` between updates in the meantime if you really do need it.

**Comment by ubergeek77** [comment]
Hello @LRMAN0989 !

While I have removed the variable you have been using from the default `docker-compose.yml`, I have added a feature to Lemmy-Easy-Deploy that allows you to specify custom environment variables for any service. Please see the release notes for how to use this feature:

https://github.com/ubergeek77/Lemmy-Easy-Deploy/releases/tag/1.2.3

Let me know if you have any questions!
